$(document).ready(function(){
  $("#a1").click(
   function(){
	$(".Ans").hide();
});
  $("#key1").click(function(){
    $("#an1").show();
  });
  $("#key2").click(function(){
    $("#an2").show();
  });
    $("#key3").click(function(){
    $("#an3").show();
  });
      $("#key4").click(function(){
    $("#an4").show();
  });
      $("#key5").click(function(){
    $("#an5").show();
  });
      $("#key6").click(function(){
    $("#an6").show();
  });
      $("#key7").click(function(){
    $("#an7").show();
  });
      $("#key8").click(function(){
    $("#an8").show();
  });
      $("#key9").click(function(){
    $("#an9").show();
  });
     $("#key10").click(function(){
    $("#an10").show();
  });
     $("#key11").click(function(){
    $("#an11").show();
  });	
});
